apiVersion: apps/v1
kind: Deployment
metadata:
  name: ooshandler
spec:
  template:
    spec:
      volumes:
        - persistentVolumeClaim:
            claimName: oos
          name: data
      containers:
        - name: ooshandler
          volumeMounts:
            - mountPath: /data
              name: data
