apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontier
  labels:
    app.kubernetes.io/name: frontier
    app.kubernetes.io/component: frontier
  annotations:
    sidecar.jaegertracing.io/inject: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: frontier
      app.kubernetes.io/component: frontier
  template:
    metadata:
      labels:
        app.kubernetes.io/name: frontier
        app.kubernetes.io/component: frontier
      annotations:
        linkerd.io/inject: enabled
    spec:
      volumes:
        - name: workdir
          emptyDir: {}
        - name: log4j2
          configMap:
            name: frontier
            items:
              - key: log4j2.xml
                path: log4j2.xml

      terminationGracePeriodSeconds: 600

      containers:
        - name: frontier
          image: ghcr.io/nationallibraryofnorway/veidemann/frontier:0.16.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 7700
              name: grpc
              protocol: TCP
            - containerPort: 9301
              name: http-metrics
              protocol: TCP
          resources:
            limits:
              cpu: "1"
              memory: 2Gi
            requests:
              cpu: 100m
              memory: 1Gi
          envFrom:
            - secretRef:
                name: rethinkdb-env
                optional: false
          env:
            - name: DB_HOST
              value: "rethinkdb-client"
            - name: DB_PORT
              value: "28015"
            - name: DB_NAME
              value: "veidemann"
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
            - name: API_PORT
              value: "7700"
            - name: ROBOTS_EVALUATOR_HOST
              value: "robots"
            - name: ROBOTS_EVALUATOR_PORT
              value: "7053"
            - name: DNS_RESOLVER_HOST
              value: "dns-resolver"
            - name: DNS_RESOLVER_PORT
              value: "8053"
            - name: SCOPESERVICE_HOST
              value: "scopeservice"
            - name: SCOPESERVICE_PORT
              value: "8080"
            - name: OOS_HANDLER_HOST
              value: "ooshandler"
            - name: OOS_HANDLER_PORT
              value: "50052"
            - name: LOG_SERVICE_HOST
              value: "log-service"
            - name: LOG_SERVICE_PORT
              value: "8080"
            - name: TERMINATION_GRACE_PERIOD_SECONDS
              value: "300"
            # - name: JAVA_OPTS
            #  value: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=34774
            #    -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/workdir/heapdump
            - name: JAEGER_SERVICE_NAME
              value: frontier
            - name: JAEGER_AGENT_HOST
              value: localhost
            - name: JAEGER_AGENT_PORT
              value: "6831"
            - name: JAEGER_SAMPLER_TYPE
              value: remote
            - name: JAEGER_SAMPLER_PARAM
              value: "0.1"
            - name: JAVA_TOOL_OPTIONS
              value: -Dfile.encoding=UTF-8 -XX:MinRAMPercentage=50.0 -XX:MaxRAMPercentage=75.0
          volumeMounts:
            - mountPath: /workdir
              name: workdir
            - mountPath: /veidemann/config/log4j2.xml
              name: log4j2
              subPath: log4j2.xml
          readinessProbe:
            grpc:
              port: 7700
            initialDelaySeconds: 1
            periodSeconds: 1
            failureThreshold: 3
          livenessProbe:
            grpc:
              port: 7700
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
