apiVersion: v1
kind: Service
metadata:
  name: frontier
  labels:
    app.kubernetes.io/name: frontier
    app.kubernetes.io/component: frontier
    metrics: prometheus
spec:
  type: ClusterIP
  ports:
    - port: 7700
      name: grpc
      targetPort: grpc
    - name: http-metrics
      port: 9301
      protocol: TCP
      targetPort: http-metrics
  selector:
    app.kubernetes.io/name: frontier
    app.kubernetes.io/component: frontier
