apiVersion: v1
kind: Service
metadata:
  name: harvester
  labels:
    app.kubernetes.io/name: harvester
    app.kubernetes.io/component: harvester
    metrics: prometheus
  annotations:
    config.linkerd.io/opaque-ports: "8080"
spec:
  type: ClusterIP
  ports:
    - name: proxy
      port: 8080
      protocol: TCP
      targetPort: proxy
    - name: http-metrics
      port: 9301
      protocol: TCP
      targetPort: http-metrics
    - name: http-debug
      port: 3000
      targetPort: debug
  selector:
    app.kubernetes.io/name: harvester
    app.kubernetes.io/component: harvester
