apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-service
spec:
  template:
    spec:
      containers:
        - name: log-service
          env:
            - name: NOOP
              value: "true"
