---

kind: ServiceAccount
apiVersion: v1
metadata:
  name: olricd

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: olricd
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "list"]

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: olricd
subjects:
  - kind: ServiceAccount
    name: olricd
roleRef:
  kind: Role
  name: olricd
  apiGroup: rbac.authorization.k8s.io
