apiVersion: v1
kind: Service
metadata:
  name: olric
spec:
  clusterIP: None
  selector:
    app: olric
  ports:
    - name: api
      port: 3320
      targetPort: api
    - name: gossip
      port: 3322
      targetPort: gossip

---

apiVersion: v1
kind: Service
metadata:
  name: olric-client
spec:
  type: ClusterIP
  selector:
    app: olric
  ports:
    - port: 3320
      protocol: TCP
      targetPort: api
