apiVersion: v1
kind: Service
metadata:
  name: robots
  labels:
    app.kubernetes.io/name: robots
spec:
  type: ClusterIP
  ports:
    - name: grpc
      port: 7053
      targetPort: grpc
      protocol: TCP
  selector:
    app.kubernetes.io/name: robots
