apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: veidemann
resources:
  - servicemonitor.yaml
  - ../../../base/rethinkdb-exporter
  - ../../../base/veidemann-grafana
  - ../../../base/veidemann-metrics
  - grafana.yaml
