---
apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    app.kubernetes.io/name: api
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  ports:
    - port: 7700
      name: grpc
      targetPort: grpc
  selector:
    app.kubernetes.io/name: controller
    app.kubernetes.io/component: controller
---
apiVersion: v1
kind: Service
metadata:
  name: api-grpc-web
  labels:
    app.kubernetes.io/name: api-grpc-web
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  ports:
    - port: 10000
      name: http-grpc-web
      targetPort: grpc-web
      protocol: TCP
  selector:
    app.kubernetes.io/name: controller
    app.kubernetes.io/component: controller
