name: Protobuf Code Generation

on:
  push:
    branches:
      - 'main'
    tags:
      - 'proto/*'
    paths:
      - 'proto/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-go@v6
        with:
          go-version: 'stable'

      - name: Generate golang code from proto files
        shell: bash
        working-directory: api
        run: go generate

      - name: Generate javascript code from proto files
        shell: bash
        working-directory: dashboard/src/api
        run: make all
