name: Browser Controller Release

on:
  push:
    tags:
      - "browser-controller-v[0-9]+.[0-9]+.[0-9]+*"
  workflow_dispatch:

jobs:
  release:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/build-and-publish-full-context.yaml
    with:
      path: browser-controller
