name: Browser Controller

on:
  push:
    branches:
      - 'main'
    tags:
      - 'browser-controller/*'
    paths:
      - 'browser-controller/**'
  pull_request:
    paths:
      - 'browser-controller/**'
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/golang-test
        with:
          working-directory: browser-controller
      - uses: ./.github/actions/golang-lint
        with:
          working-directory: browser-controller

  build:
    needs: test
    if: github.event_name != 'pull_request'
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/build-and-publish-full-context.yaml
    with:
      PATH: browser-controller
