name: Browser Controller

on:
  push:
    branches:
      - "main"
    tags:
      - "browser-controller-*"
    paths:
      - "browser-controller/**"
  pull_request:
    paths:
      - "browser-controller/**"
  workflow_dispatch:

jobs:
  ci:
    uses: ./.github/workflows/golang-ci.yaml
    with:
      working-directory: browser-controller

  release:
    needs: ci
    if: github.event_name != 'pull_request'
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/build-and-publish-full-context.yaml
    with:
      path: browser-controller
