name: Cache

on:
  push:
    branches:
      - 'main'
    tags:
      - 'cache/*'
    paths:
      - 'cache/**'
  workflow_dispatch:

jobs:

  test:
    name: Test Helpers
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Checkout code
        uses: ./.github/actions/golang-test
        with:
          working-directory: cache/helpers

  build:
    needs: test
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/build-and-publish.yaml
    with:
      PATH: cache
