name: Controller

on:
  push:
    branches:
      - 'main'
    tags:
      - 'controller-*'
    paths:
      - 'controller/**'
  pull_request:
    paths:
      - 'controller/**'
  workflow_dispatch:

jobs:
  release:
    if: github.event_name != 'pull_request'
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/build-and-publish-java.yaml
    with:
      path: controller
