name: veidemannctl

on:
  push:
    branches:
      - 'main'
    tags:
      - 'ctl-*'
    paths:
      - 'ctl/**'
  pull_request:
    paths:
      - 'ctl/**'
  workflow_dispatch:

jobs:
  ci:
    uses: ./.github/workflows/golang-ci.yaml
    with:
      working-directory: ctl

  release:
    needs: ci
    uses: ./.github/workflows/build-and-release.yaml
    with:
      PATH: ctl
