name: veidemannctl

on:
  push:
    branches:
      - 'main'
    tags:
      - 'ctl/*'
    paths:
      - 'ctl/**'
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/golang-test
        with:
          working-directory: ctl
      - uses: ./.github/actions/golang-lint
        with:
          working-directory: ctl

  build:
    needs: test
    uses: ./.github/workflows/build-and-release.yaml
    with:
      PATH: ctl
