name: veidemannctl Release

on:
  push:
    tags:
      - 'ctl-v[0-9]+.[0-9]+.[0-9]+*'
  workflow_dispatch:

jobs:
  release:
    uses: ./.github/workflows/build-and-release.yaml
    with:
      path: ctl
