name: DNS Resolver CI

on:
  push:
    branches:
      - 'main'
    paths:
      - 'dns-resolver/**'
  pull_request:
    paths:
      - 'dns-resolver/**'
  workflow_dispatch:

jobs:
  ci:
    uses: ./.github/workflows/golang-ci.yaml
    with:
      working-directory: dns-resolver
