name: DNS Resolver

on:
  push:
    branches:
      - 'main'
    tags:
      - 'dns-resolver-*'
    paths:
      - 'dns-resolver/**'
  pull_request:
    paths:
      - 'dns-resolver/**'
  workflow_dispatch:

jobs:
  ci:
    uses: ./.github/workflows/golang-ci.yaml
    with:
      working-directory: dns-resolver

  release:
    needs: ci
    if: github.event_name != 'pull_request'
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/build-and-publish.yaml
    with:
      path: dns-resolver
