name: Frontier Queue Workers

on:
  push:
    branches:
      - 'main'
    tags:
      - 'frontier-queue-workers-*'
    paths:
      - 'frontier-queue-workers/**'
  pull_request:
    paths:
      - 'frontier-queue-workers/**'
  workflow_dispatch:

jobs:
  ci:
    uses: ./.github/workflows/golang-ci.yaml
    with:
      working-directory: frontier-queue-workers

  release:
    needs: ci
    if: github.event_name != 'pull_request'
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/build-and-publish.yaml
    with:
      path: frontier-queue-workers
