name: Frontier CI

on:
  push:
    branches:
      - 'main'
    paths:
      - 'frontier/**'
  pull_request:
    paths:
      - 'frontier/**'
  workflow_dispatch:

jobs:
  ci:
    uses: ./.github/workflows/java-ci.yaml
    with:
      subproject: frontier
