name: Frontier Release

on:
  push:
    tags:
      - 'frontier-v[0-9]+.[0-9]+.[0-9]+*'
  workflow_dispatch:

jobs:
  release:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/build-and-publish-java.yaml
    with:
      path: frontier
