name: Frontier Queue Workers

on:
  push:
    branches:
      - 'main'
    tags:
      - 'frontier-queue-workers/*'
    paths:
      - 'frontier-queue-workers/**'
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/golang-test
        with:
          working-directory: frontier-queue-workers
      - uses: ./.github/actions/golang-lint
        with:
          working-directory: frontier-queue-workers

  build:
    needs: test
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/build-and-publish.yaml
    with:
      PATH: frontier-queue-workers
