name: Log Service

on:
  push:
    branches:
      - 'main'
    tags:
      - 'log-service-*'
    paths:
      - 'log-service/**'
  pull_request:
    paths:
      - 'log-service/**'
  workflow_dispatch:

jobs:
  ci:
    uses: ./.github/workflows/golang-ci.yaml
    with:
      working-directory: log-service

  release:
    needs: ci
    if: github.event_name != 'pull_request'
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/build-and-publish.yaml
    with:
      path: log-service
