name: Log Service CI

on:
  push:
    branches:
      - 'main'
    paths:
      - 'log-service/**'
  pull_request:
    paths:
      - 'log-service/**'
  workflow_dispatch:

jobs:
  ci:
    uses: ./.github/workflows/golang-ci.yaml
    with:
      working-directory: log-service
