name: Metrics

on:
  push:
    branches:
      - 'main'
    tags:
      - 'metrics-*'
    paths:
      - 'metrics/**'
  pull_request:
    paths:
      - 'metrics/**'
  workflow_dispatch:

jobs:
  ci:
    uses: ./.github/workflows/golang-ci.yaml
    with:
      working-directory: metrics

  release:
    needs: ci
    if: github.event_name != 'pull_request'
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/build-and-publish.yaml
    with:
      PATH: metrics
