name: OOS Handler

on:
  push:
    branches:
      - 'main'
    tags:
      - 'ooshandler/*'
    paths:
      - 'ooshandler/**'
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/golang-test
        with:
          working-directory: ooshandler
      - uses: ./.github/actions/golang-lint
        with:
          working-directory: ooshandler

  build:
    needs: test
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/build-and-publish.yaml
    with:
      PATH: ooshandler
