name: Recorder Proxy Release

on:
  push:
    tags:
      - 'recorderproxy-v[0-9]+.[0-9]+.[0-9]+*'
  workflow_dispatch:

jobs:
  release:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/build-and-publish-full-context.yaml
    with:
      path: recorderproxy
