name: Recorder Proxy CI

on:
  push:
    branches:
      - 'main'
    paths:
      - 'recorderproxy/**'
  pull_request:
    paths:
      - 'recorderproxy/**'
  workflow_dispatch:

jobs:
  ci:
    uses: ./.github/workflows/golang-ci.yaml
    with:
      working-directory: recorderproxy
