name: RethinkDB CI

on:
  push:
    branches:
      - 'main'
    paths:
      - 'rethinkdb/**'
  pull_request:
    paths:
      - 'rethinkdb/**'
  workflow_dispatch:

jobs:
  ci:
    uses: ./.github/workflows/golang-ci.yaml
    with:
      working-directory: rethinkdb/probe
