name: Robots Evaluator CI

on:
  push:
    branches:
      - 'main'
    paths:
      - 'robots-evaluator/**'
  pull_request:
    paths:
      - 'robots-evaluator/**'
  workflow_dispatch:

jobs:
  ci:
    uses: ./.github/workflows/golang-ci.yaml
    with:
      working-directory: robots-evaluator
