---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: veidemann
spec:
  isCA: true
  commonName: "*.veidemann.test"
  secretName: veidemann-tls
  dnsNames:
    - "veidemann.test"
    - "*.veidemann.test"
  issuerRef:
    name: selfsigned
    kind: Issuer
  subject:
    organizations:
      - veidemann
